export interface DataTile {
        Title: string,
        Year: number,
        Rated: string,
        Released: string,
        Runtime: string,
        Genre: string,
        Director: string,
        Writer: string,
        Actors: string,
        Plot: string,
        Language: string,
        Country: string,
        Awards: string,
        Poster: string,
        Ratings: [],
        Metascore: 67,
        imdbRating: 7.6,
        imdbVotes: number,
        imdbID: string,
        Type: string,
        DVD: string,
        BoxOffice: number,
        Production: string,
        Website: string,
        Response: string
}