import {DataTile} from './dataTile';

export const MOCKDATA: DataTile[] = [
  {
    Title: "Guardians of the Galaxy",
    Year: 2011,
    Rated: "R",
    Released: "foobooo",
    Runtime: "foobooo",
    Genre: "Action",
    Director: "foobooo",
    Writer: "foobooo",
    Actors: "foobooo",
    Plot: "foobooo",
    Language: "foobooo",
    Country: "foobooo",
    Awards: "foobooo",
    Poster: "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
    Ratings: [],
    Metascore: 67,
    imdbRating: 7.6,
    imdbVotes: 10000,
    imdbID: "foobooo",
    Type: "movie",
    DVD: "foobooo",
    BoxOffice: 10000,
    Production: "foobooo",
    Website: "foobooo",
    Response: "foobooo"
    },
    {
      Title: "Out Cold",
      Year: 2001,
      Rated: "R",
      Released: "foobooo",
      Runtime: "foobooo",
      Genre: "Comedy",
      Director: "foobooo",
      Writer: "foobooo",
      Actors: "foobooo",
      Plot: "foobooo",
      Language: "foobooo",
      Country: "foobooo",
      Awards: "foobooo",
      Poster: "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
      Ratings: [],
      Metascore: 67,
      imdbRating: 7.6,
      imdbVotes: 10000,
      imdbID: "foobooo",
      Type: "movie",
      DVD: "foobooo",
      BoxOffice: 10000,
      Production: "foobooo",
      Website: "foobooo",
      Response: "foobooo"
      },
      {
        Title: "The Sopranos",
        Year: 2007,
        Rated: "R",
        Released: "foobooo",
        Runtime: "foobooo",
        Genre: "Action",
        Director: "foobooo",
        Writer: "foobooo",
        Actors: "foobooo",
        Plot: "foobooo",
        Language: "foobooo",
        Country: "foobooo",
        Awards: "foobooo",
        Poster: "https://m.media-amazon.com/images/M/MV5BNjM0NTc0NzItM2FlYS00YzEwLWE0YmUtNTA2ZWIzODc2OTgxXkEyXkFqcGdeQXVyNTgwNzIyNzg@._V1_SX300.jpg",
        Ratings: [],
        Metascore: 67,
        imdbRating: 7.6,
        imdbVotes: 10000,
        imdbID: "foobooo",
        Type: "series",
        DVD: "foobooo",
        BoxOffice: 10000,
        Production: "foobooo",
        Website: "foobooo",
        Response: "foobooo"
        }
  ]
  